Systemd update
debloper/piosk pull request #62
Opened 2024-12-19 20:16 UTC by SpiraMirabilis

This PR updates the piosk to use systemd services to manage the three scripts the piosk uses to function. This involved completely re-writing the setup.sh and cleanup.sh, as a result the new setup.sh installs a copy of the package in /opt/piosk and configures all the scripts to run from there.

One change is the way this setup.sh works now means you shouldn't curl it to run it, you should always git clone and then execute the setup.sh inside of the cloned repository. You can change that if you want but I didn't feel like bothering.

Sorry about changing the swithcer.sh sleep to 30, I did this for testing because I thought it was annoying to switch so quickly and didn't notice. Feel free to adjust that back.

2024-12-19 20:39 UTC, SpiraMirabilis commented
I just realised there is a bug in the second commit, namely in setup.sh the last systemctl enable does piosk-browser a second time, when it should be piosk-webserver. This means the webserver will never get enabled. I honestly have no idea how to make changes to a PR when its already been submitted, so you'll either need to make this change yourself or close the PR and I can resubmit it.

2024-12-19 20:44 UTC, SpiraMirabilis commented
Oh, I figured out how. lol

2024-12-19 22:39 UTC, debloper commented
Whoa... nice! Thanks for the PR. 🙏

I'll review (and test) it over the weekend and then merge it ASAP.

2024-12-30 21:53 UTC, kiyose commented on scripts/setup.sh
> -        mv piosk/config.json.sample piosk/config.json
This line has not been carried forward.  Currently a fresh install will fail due to a missing `config.json` file in /opt/piosk.

2024-12-31 00:13 UTC, SpiraMirabilis commented
oops. i hit the wrong button.

2024-12-31 21:07 UTC, debloper requested changes
Happy New Year... I know it's later than I promised, but I got back to it as soon as I could. Trust me, it's local time 2am of the new year morning, and I'm testing & reviewing shell scripts instead of getting pissed & hungover like a normal person.

# Excellent Enhancements

Love them!

- **Systemd Integration:** Replaced manual process management with systemd service units.
- **Compositor Agnostic:** Doesn't rely on Wayfire (or labwc) for running the startup scripts.
- **Centralized Installation:** Moved application runtime files to `/opt/piosk` (dropping per-user installation as moot).
- **Autologin Verification:** Added checks to ensure autologin is configured.
- **Superuser Autoescalation:** Try to automatically run the script with sudo if missed by user.

# Relevant Recommendations

Non-critical... I'll do it, if you don't.

- **Redundant Checks:** Enough to verify autologin status just once (it's being done twice).
- **Rename Templates:** Rename the directory to `services` or `daemons` instead of `templates` (update scripts to reflect).
- **Documentation Updates:** Update docs to reflect these changes (especially Wayfire dependency part).


# Breaking Bugs

Can't merge without fixing these first:

- **Reimplement One-liner:** Don't expects user(s) to have pre-cloned the repo locally to run setup. Allow [copying installation oneliner](https://github.com/debloper/piosk/blob/4e3fd3ed3e9732a81b15c7259a571c17876ce657/README.md?plain=1#L56) & clone repo through setup script (like it was before).
- **Handle Configurations:**
  - **Preset config.json:** After setup, [copy or rename](https://github.com/debloper/piosk/blob/4e3fd3ed3e9732a81b15c7259a571c17876ce657/scripts/setup.sh#L27) `config.json.sample` to `config.json` to seed dashboard config.
  - **Restore Backup:** If a backup config is found, [restore it instead](https://github.com/debloper/piosk/blob/4e3fd3ed3e9732a81b15c7259a571c17876ce657/scripts/setup.sh#L25) of seeding from sample file.
  - **Backup Config:** Instead of putting it as a random `config.json.bak` file in the homedir, [use namespace](https://github.com/debloper/piosk/blob/4e3fd3ed3e9732a81b15c7259a571c17876ce657/scripts/cleanup.sh#L4) for clarity.
- **Report HOST/IP:** On installation completion, [show formatted hostname and IP as URLs](https://github.com/debloper/piosk/blob/4e3fd3ed3e9732a81b15c7259a571c17876ce657/scripts/setup.sh#L48), for users to setup from another system.

---

With that said, I must add that including too many changes in a single pull request is just calling for trouble. It's hard to manage, test, review and merge (and needs more back and forth changes, and halts merging the parts that are already good to ship). So, for future PRs, please consider fixing one (and preferably only one) thing at a time with a single PR.

However, great work in this one. Especially like the QoL changes you've made (like autologin check, superuser escalation, terminal colors with `tput` etc). Highly appreciated!

2025-02-22 06:09 UTC, debloper commented
This PR needs a bit of cleanup and addition before it can go live.

Today I've found some time and working with an RPi5 4GiB model. Hope to finish the work in one sitting, but in case I can't... I don't wanna leave the main branch in a limbo by merging the PR & breaking the installer for people trying to run the script.

So, I'm going to manage this PR manually instead:

- [x] Create & switch to local `devel` branch
- [x] Fetch [`SpiraMirabilis:main`](https://github.com/SpiraMirabilis/piosk/tree/main)
- [x] Merge `SpiraMirabilis:main` to `devel`
- [x] Push `devel` to [`debloper:devel`](https://github.com/debloper/piosk/commits/devel/)
- [ ] Append commits to `devel` for cleanup & fixes (addressing the review comments)
- [ ] Test and verify the updated script to work from `devel` branch
- [ ] Update docs/readme to reflect changes & update setup script to use release version instead of main `HEAD`
- [ ] Merge and push `devel` to `main`
- [ ] Create release & retest to ensure it's OK

> [!NOTE]
> I'm only closing this pull request, cause I can't change the target branch to `devel` from the web-gui. This PR is **accepted with thanks**, as it brings net positive changes.

2025-02-22 06:09 UTC, closed without merging